import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'java-library'
    id 'jacoco'
    alias(printLibs.plugins.kotlin.jvm)
}

group = 'eu.pretix.pretixdesk'
version = '1.0'



kotlin {
    compilerOptions.jvmTarget.set(JvmTarget.JVM_11)
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}


jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

check.dependsOn jacocoTestReport

repositories {
    mavenCentral()
}

dependencies {
    implementation printLibs.openpdf
    implementation printLibs.zxing.core

    // Use older org.json version to have an environment equivalent to the android platform
    implementation printLibs.json

    testImplementation printLibs.junit
}

tasks.register('copyTestResources', Copy) {
    from "${projectDir}/src/test/resources", "${projectDir}/src/main/resources"
    into layout.buildDirectory.dir("classes/test")
}
processTestResources.dependsOn copyTestResources